### ISSUE TITLE
Parametric path of `.npmrc` file

### ISSUE THREAD

**Issue by maerzhase** [FerLuisxd/create-npmrc#1]
Hej thanks for this piece of code 🍰!
I am wondering: Would you find it valuable to make the path of the file a user defined parameter? 

This comes in handy when you want to use this action inside a mono-repo and you need to create the `.npmrc` in the e.g. `/www` folder.

Or am I missing the obvious?

**Comment by PeterAronZentai** [comment]
you are.. npm itself isn't supporting custom npmrc file locations :(

**Comment by maerzhase** [comment]
i am not talking about custom `.npmrc` file locations. I am talking about mono repositories where the frontend is not in the main root of the repository but in a subfolder.

**Comment by FerLuisxd** [comment]
Sorry for the late response

You mean to have projects in subfolders? Actually I would consider that bad practice, you normally want one repository per project.
But I think it might be possible, I'll think about it

**Comment by maerzhase** [comment]
sorry but this is such a stupid argument! mono-repositories are such a common usecase. just because u dont know/use them they are not a bad practice. people build projects on gh that are also not libraries. e.g. apps. apps consist of multiple components: backend, frontend, storage, etc.
