### ISSUE TITLE
Generated .npmrc is missing the organisation Prefix

### ISSUE THREAD

**Issue by achyutjhunjhunwala** [FerLuisxd/create-npmrc#2]
I have using this plugin for long and now suddenly it started breaking. After analysing I found thee root cause with which i am able to reproduce the issue locally as well.

I have a private package hosted on Github Packages. 

I want just this package to be installed using the org registry url and rest packages from public nom registry. The problem is the output generated by this plugin is

```
//npm.pkg.github.com/:_authToken=long_token
registry=https://npm.pkg.github.com
```

Where as for the above to work, we need the output like this

```
//npm.pkg.github.com/:_authToken=long_token
@myOrg:registry=https://npm.pkg.github.com
```

Since its missing the `@myOrg:` prefix, it tries to install all other npm public packages also via the private registry which is why they fail.

**Comment by FerLuisxd** [comment]
I've released a new version to address this. should be used with ferluisxd/create-npmrc@4.
Please confirm that this fixed the issue! :D
It was a nice job @achyutjhunjhunwala
